env:
   global:
     - CONAN_USERNAME: "maxxboehme"
     - CONAN_CHANNEL: "testing"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches CONAN_STABLE_BRANCH_PATTERN

before_script: &cmake_before_script
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE${BUILD_TYPE}

script: &cmake_script
  - cmake --build .
  - ctest --output-on-failure

install: &conan_install
  - chmod +x conan/.travis/install.sh
  - ./conan/.travis/install.sh

script: &conan_script
  - chmod +x conan/.travis/run.sh
  - ./conan/.travis/run.sh

linux: &linux_cmake
   os: linux
   dist: xenial
   addons:
       apt:
           sources:
               - ubuntu-toolchain-r-test
           packages:
               - g++-6
               - g++-7
               - g++-8
   # No language, so that we can set CXX and CC env vars as needed ourselves
   services:
     - docker
   install: *conan_install # We still need conan installed
   before_script: *cmake_before_script
   script: *cmake_script

linux: &linux_conan
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
   before_script: *cmake_before_script
   script: *cmake_script

osx: &osx_conan
   os: osx
   language: generic
   install: *conan_install
   script: *conan_script

matrix:
   fast_finish: true
   include:

      - <<: *linux_cmake
        env:
            - CC='gcc-6'
            - CXX='g++-6'
            - BUILD_TYPE='Release'

      - <<: *linux_cmake
        env:
            - CC='gcc-6'
            - CXX='g++-6'
            - BUILD_TYPE='Debug'

      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6

      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=conanio/clang50

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang70

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=7.1 CONAN_DOCKER_IMAGE=conanio/clang71

      - <<: *osx_conan
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

