env:
   global:
     - CONAN_USERNAME: "maxxboehme"
     - CONAN_CHANNEL: "testing"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches CONAN_STABLE_BRANCH_PATTERN

cmake_before_script: &cmake_before_script
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

cmake_script: &cmake_script
  - cmake --build .
  - ctest --output-on-failure

conan_install: &conan_install
  - chmod +x conan/.travis/install.sh
  - ./conan/.travis/install.sh

conan_script: &conan_script
  - chmod +x conan/.travis/run.sh
  - ./conan/.travis/run.sh

linux_cmake: &linux_cmake
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   addons:
       apt:
           sources:
               - ubuntu-toolchain-r-test
           packages:
               - g++-6
               - g++-7
               - g++-8
   # No language, so that we can set CXX and CC env vars as needed ourselves
   services:
     - docker
   install: *conan_install # We still need conan installed
   before_script: *cmake_before_script
   script: *cmake_script

linux_conan: &linux_conan
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
   install: *conan_install
   script: *conan_script

osx_conan: &osx_conan
   os: osx
   language: generic
   install: *conan_install
   script: *conan_script

matrix:
   fast_finish: true
   include:

      # Validate that project can be made just using cmake process
# [TODO] Disabled cmake builds until figuring out if can use a lower level
# or install newer cmake
#      - <<: *linux_cmake
#        env:
#            - CC='gcc-6'
#            - CXX='g++-6'
#            - BUILD_TYPE='Release'
#
#      - <<: *linux_cmake
#        env:
#            - CC='gcc-6'
#            - CXX='g++-6'
#            - BUILD_TYPE='Debug'

      # Create conan packages for multiple compilers
      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7

      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux_conan
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8

      - <<: *linux_conan
        env: CONAN_CLANG_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/clang9

      - <<: *osx_conan
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

      - <<: *osx_conan
        osx_image: xcode11
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

