build: false

environment:
    PYTHON: "C:\\Python38"

    CONAN_USERNAME: "maxxboehme"
    CONAN_LOGIN_USERNAME: "mboehme.jfrog@gmail.com"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD: https://mboehme.jfrog.io/artifactory/api/conan/mboehme-conan

    matrix:
        # First Visual Studio version to support C++17
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python conan/build.py
