build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_USERNAME: "maxxboehme"
    CONAN_LOGIN_USERNAME: "maxxboehme.jfrog@gmail.com"
    CONAN_CHANNEL: "testing"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD: https://maxxboehme.jfrog.io/artifactory/api/conan/packages-conan-local

    matrix:
        # First Visual Studio version to support C++17
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python conan/build.py
